/**
 * learning-path.ts
 * -------------------------------------------------------------
 * The deterministic part of the InfoPath loop:
 *
 *   Placement Test -> Skill Profile -> Learning Goals -> Learning Path
 *   -> Content (course/video/challenge/project) -> Assessment
 *   -> Skill update -> new goals / recommendations
 *
 * IMPORTANT: the steps of a Learning Path are NOT generated by AI.
 * The instructor builds a *path template* for a skill/level from the content
 * they published, and the platform copies that template into the student's
 * personal path when the skill becomes their current goal.
 * AI only orders the weak skills and drafts content the instructor reviews.
 */
import { useQuery } from "@tanstack/react-query";

import { supabase } from "@/integrations/supabase/client";

export type Difficulty = "easy" | "medium" | "hard";

/** Level a student must reach before a skill counts as "solid". */
export const TARGET_LEVEL = 70;

/** Difficulty the student should start with, given their current level. */
export function difficultyForLevel(level: number): Difficulty {
  if (level < 40) return "easy";
  if (level < TARGET_LEVEL) return "medium";
  return "hard";
}

/** todo -> in_progress -> submitted (waiting for the instructor) -> done */
export type PathStatus = "todo" | "in_progress" | "submitted" | "done";

export type PathItem = {
  id: string;
  skill_key: string | null;
  subject_id: string | null;
  item_type: "resource" | "project" | "challenge" | "quiz";
  item_id: string | null;
  title_ar: string;
  title_en: string;
  body_ar: string | null;
  body_en: string | null;
  level: Difficulty;
  step_order: number;
  status: string;
  started_at: string | null;
  progress_note: string | null;
  progress_percent: number;
};

/** The student's active learning goals (weak skills), weakest first. */
export function useLearningGoals(userId: string | undefined) {
  return useQuery({
    queryKey: ["learning-goals", userId],
    enabled: Boolean(userId),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("learning_goals")
        .select("*")
        .eq("user_id", userId!)
        .order("priority");
      if (error) throw error;
      return data;
    },
  });
}

/** Ordered steps of the personalised learning path. */
export function useLearningPath(userId: string | undefined) {
  return useQuery({
    queryKey: ["learning-path", userId],
    enabled: Boolean(userId),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("learning_path_items")
        .select("*")
        .eq("user_id", userId!)
        .order("step_order");
      if (error) throw error;
      return (data ?? []) as PathItem[];
    },
  });
}

/** Initial / current / final skill snapshots used by the progress comparison. */
export function useSkillSnapshots(userId: string | undefined) {
  return useQuery({
    queryKey: ["skill-snapshots", userId],
    enabled: Boolean(userId),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("skill_snapshots")
        .select("phase, skill_key, level, created_at")
        .eq("user_id", userId!)
        .order("created_at");
      if (error) throw error;
      return data ?? [];
    },
  });
}

/** Stores a snapshot of the whole skill profile (initial / current / final). */
export async function saveSkillSnapshot(
  userId: string,
  phase: "initial" | "current" | "final",
  levels: Record<string, number>,
) {
  const rows = Object.entries(levels).map(([skill_key, level]) => ({
    user_id: userId,
    phase,
    skill_key,
    level: Math.round(level),
  }));
  if (rows.length === 0) return;
  // one snapshot set per phase: replace the previous one
  await supabase.from("skill_snapshots").delete().eq("user_id", userId).eq("phase", phase);
  const { error } = await supabase.from("skill_snapshots").insert(rows);
  if (error) throw error;
}

/** Marks a path step done (and re-opens it when `done` is false). */
export async function setPathItemStatus(id: string, status: PathStatus) {
  const patch: {
    status: string;
    started_at?: string | null;
    progress_percent?: number;
  } = { status };
  if (status === "in_progress") patch.started_at = new Date().toISOString();
  if (status === "todo") {
    patch.started_at = null;
    patch.progress_percent = 0;
  }
  if (status === "done") patch.progress_percent = 100;
  const { error } = await supabase.from("learning_path_items").update(patch).eq("id", id);

  if (error) throw error;
}

/* ------------------------------------------------------------------ */
/* Progress updates: the student reports what they are actually doing  */
/* ------------------------------------------------------------------ */

export type PathUpdate = {
  id: string;
  user_id: string;
  author_id: string;
  path_item_id: string | null;
  skill_key: string | null;
  percent: number;
  body: string;
  created_at: string;
};

/** Progress updates of one student (their own view, or the instructor's). */
export function usePathUpdates(userId: string | undefined, pathItemId?: string) {
  return useQuery({
    queryKey: ["path-updates", userId, pathItemId ?? "all"],
    enabled: Boolean(userId),
    queryFn: async () => {
      let query = supabase
        .from("path_updates")
        .select("*")
        .eq("user_id", userId!)
        .order("created_at", { ascending: false });
      if (pathItemId) query = query.eq("path_item_id", pathItemId);
      const { data, error } = await query;
      if (error) throw error;
      return (data ?? []) as PathUpdate[];
    },
  });
}

/**
 * Posts a progress update. The student writes about their own step; the
 * instructor writes a reply on the same thread (RLS enforces both cases).
 */
export async function sendPathUpdate(input: {
  studentId: string;
  authorId: string;
  pathItemId: string | null;
  skillKey: string | null;
  percent: number;
  body: string;
}) {
  const body = input.body.trim();
  if (!body) return;
  const percent = Math.max(0, Math.min(100, Math.round(input.percent)));
  const { error } = await supabase.from("path_updates").insert({
    user_id: input.studentId,
    author_id: input.authorId,
    path_item_id: input.pathItemId,
    skill_key: input.skillKey,
    percent,
    body,
  });
  if (error) throw error;

  // keep the step itself in sync so the instructor sees it at a glance
  if (input.pathItemId && input.authorId === input.studentId) {
    await supabase
      .from("learning_path_items")
      .update({ progress_percent: percent, progress_note: body })
      .eq("id", input.pathItemId);
  }
}

/* ------------------------------------------------------------------ */
/* Instructor-authored path templates                                  */
/* ------------------------------------------------------------------ */

export type PathTemplate = {
  id: string;
  skill_key: string;
  level: Difficulty;
  title_ar: string;
  title_en: string;
  published: boolean;
  created_by: string | null;
};

export type PathTemplateItem = {
  id: string;
  template_id: string;
  subject_id: string | null;
  item_type: "resource" | "project" | "challenge" | "quiz";
  item_id: string | null;
  title_ar: string;
  title_en: string;
  body_ar: string | null;
  body_en: string | null;
  level: Difficulty;
  step_order: number;
};

/** Templates the signed-in instructor/admin can see (theirs + published). */
export function usePathTemplates() {
  return useQuery({
    queryKey: ["path-templates"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("path_templates")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as PathTemplate[];
    },
  });
}

/** Ordered steps of one template. */
export function usePathTemplateItems(templateId: string | undefined) {
  return useQuery({
    queryKey: ["path-template-items", templateId],
    enabled: Boolean(templateId),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("path_template_items")
        .select("*")
        .eq("template_id", templateId!)
        .order("step_order");
      if (error) throw error;
      return (data ?? []) as PathTemplateItem[];
    },
  });
}

/**
 * Rebuilds goals + path from the current skill profile.
 *
 * Goals are ordered by the skill profile (weakest first); the STEPS are copied
 * from the template the instructor published for that skill. When a skill has
 * no template yet, no step is invented — the student simply sees
 * "the path is being prepared by your instructor".
 * Completed steps are preserved so the student never loses progress.
 */
export async function rebuildLearningPath(userId: string) {
  const [{ data: skills }, { data: profile }] = await Promise.all([
    supabase.from("skills").select("key, name_ar, name_en").order("sort_order"),
    supabase.from("skill_profile").select("skill_key, level").eq("user_id", userId),
  ]);

  const levels = new Map((profile ?? []).map((r) => [r.skill_key, r.level]));
  if (levels.size === 0) return 0;

  // Skills whose path the student already finished must not come back.
  const { data: reachedGoals } = await supabase
    .from("learning_goals")
    .select("skill_key")
    .eq("user_id", userId)
    .eq("status", "reached");
  const reached = new Set((reachedGoals ?? []).map((g) => g.skill_key));

  // 1) Goals = every skill below the target, weakest first.
  const weak = (skills ?? [])
    .map((s) => ({ ...s, level: levels.get(s.key) ?? 0 }))
    .filter((s) => s.level < TARGET_LEVEL && !reached.has(s.key))
    .sort((a, b) => a.level - b.level)
    .slice(0, 4);

  if (weak.length === 0) {
    await supabase.from("learning_goals").update({ status: "reached" }).eq("user_id", userId);
    return 0;
  }

  await supabase.from("learning_goals").upsert(
    weak.map((s, i) => ({
      user_id: userId,
      skill_key: s.key,
      start_level: s.level,
      target_level: TARGET_LEVEL,
      status: "active",
      priority: i + 1,
    })),
    { onConflict: "user_id,skill_key" },
  );

  const { data: goals } = await supabase
    .from("learning_goals")
    .select("id, skill_key")
    .eq("user_id", userId);
  const goalId = new Map((goals ?? []).map((g) => [g.skill_key, g.id]));

  // 2) The instructor-authored templates for those skills.
  const keys = weak.map((s) => s.key);
  const { data: templates } = await supabase
    .from("path_templates")
    .select("id, skill_key, level")
    .in("skill_key", keys)
    .eq("published", true)
    .order("created_at");

  const templateList = templates ?? [];
  if (templateList.length === 0) return 0;

  const { data: templateItems } = await supabase
    .from("path_template_items")
    .select("*")
    .in(
      "template_id",
      templateList.map((t) => t.id),
    )
    .order("step_order");

  // 3) Keep finished steps, rebuild the open ones.
  await supabase
    .from("learning_path_items")
    .delete()
    .eq("user_id", userId)
    .neq("status", "done");

  const { data: kept } = await supabase
    .from("learning_path_items")
    .select("item_type, item_id")
    .eq("user_id", userId);
  const keptSet = new Set((kept ?? []).map((k) => `${k.item_type}:${k.item_id}`));

  const rows: Record<string, unknown>[] = [];
  let order = 0;

  for (const skill of weak) {
    const want = difficultyForLevel(skill.level);
    const gid = goalId.get(skill.key) ?? null;

    // the template that matches the student's level, otherwise the first one
    const forSkill = templateList.filter((t) => t.skill_key === skill.key);
    const template = forSkill.find((t) => t.level === want) ?? forSkill[0];
    if (!template) continue;

    const steps = (templateItems ?? []).filter((i) => i.template_id === template.id);
    for (const step of steps) {
      if (keptSet.has(`${step.item_type}:${step.item_id}`)) continue;
      rows.push({
        user_id: userId,
        goal_id: gid,
        skill_key: skill.key,
        subject_id: step.subject_id,
        item_type: step.item_type,
        item_id: step.item_id,
        title_ar: step.title_ar,
        title_en: step.title_en,
        body_ar: step.body_ar,
        body_en: step.body_en,
        level: step.level,
        step_order: order++,
        status: "todo",
      });
    }
  }

  if (rows.length === 0) return 0;
  const { error } = await supabase.from("learning_path_items").insert(rows as never);
  if (error) throw error;
  return rows.length;
}
